name: Continuous Integration

on: [push, pull_request]

jobs:
  testFrontend:
    name: Test frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: checkout frontend folder
        run: cd app-backend
      
      - name: Install packages
        run: yarn
        
      - name: Run ESLint
        run: yarn lint

      - name: Run tests
        run: yarn test --watchAll=false

  testBackend:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2

      - name: checkout backend folder
        run: cd app-backend

      - name: Install packages
        run: yarn
        
      - name: Run ESLint
        run: yarn lint

      - name: Run tests
        run: yarn test --watchAll=false
