export const API_URL = 'http://localhost:5000';

export const LOAD_LINKS_DATA = 'LOAD_LINKS_DATA';
export const LOAD_LINKS_SUCCESS = 'LOAD_LINKS_SUCCESS';
export const LOAD_LINKS_FAILED = 'LOAD_LINKS_FAILED';

export const LOAD_LINK_DATA = 'LOAD_LINK_DATA';
export const LOAD_LINK_SUCCESS = 'LOAD_LINK_SUCCESS';
export const LOAD_LINK_FAILED = 'LOAD_LINK_FAILED';

export const LOAD_SEARCHED_LINKS_DATA = 'LOAD_SEARCHED_LINKS_DATA';
export const LOAD_SEARCHED_LINKS_SUCCESS = 'LOAD_SEARCHED_LINKS_SUCCESS';
export const LOAD_SEARCHED_LINKS_FAILED = 'LOAD_SEARCHED_LINKS_FAILED';

export const LOAD_SEARCHED_LINK_DATA = 'LOAD_SEARCHED_LINK_DATA';
export const LOAD_SEARCHED_LINK_SUCCESS = 'LOAD_SEARCHED_LINK_SUCCESS';
export const LOAD_SEARCHED_LINK_FAILED = 'LOAD_SEARCHED_LINK_FAILED';

export const ADD_LINK_DATA = 'ADD_LINK_DATA';
export const ADD_LINK_SUCCESS = 'ADD_LINK_SUCCESS';
export const ADD_LINK_FAILED = 'ADD_LINK_FAILED';

export const AUTHORIZE_USER_DATA = 'AUTHORIZE_USER_DATA';
export const AUTHORIZE_USER_SUCCESS = 'AUTHORIZE_USER_SUCCESS';
export const AUTHORIZE_USER_FAILED = 'AUTHORIZE_USER_FAILED';

export const REGISTER_USER_DATA = 'REGISTER_USER_DATA';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const EDIT_LINK_DATA = 'EDIT_LINK_DATA';
export const EDIT_LINK_FAILED = 'EDIT_LINK_DATA';
export const EDIT_LINK_SUCCESS = 'EDIT_LINK_DATA';
